# Generated by Django 2.0.5 on 2018-06-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_template',
            field=models.CharField(blank=True, choices=[('standard', 'Standard')], max_length=255, null=True),
        ),
    ]
