# Generated by Django 2.0.5 on 2018-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customforms', '0002_form_form_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='display_title',
            field=models.BooleanField(default=False, help_text='If you wish to display the title above the form fields tick this.'),
        ),
        migrations.AlterField(
            model_name='form',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by commas.', max_length=255, verbose_name='to address'),
        ),
    ]
