# Generated by Django 2.0.5 on 2018-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customforms', '0003_form_display_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='button_alignment',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], max_length=255, null=True),
        ),
    ]
